### ISSUE TITLE
Enable parallel training of models during k-fold validation

### ISSUE THREAD

**Issue by danielsf** [AllenInstitute/DeepCell#29]
Each fold takes ~ 1 hour to train. Usually we train 5-folds.

SageMaker includes a flag that allows you to turn on parallel training, but it requires you to do some querying to determine when all k-folds are finished.

This will be required for any deep learning model that we want to train on the cloud.

**Tasks**

- [ ] Write utility to query SageMaker and determine when all k-folds have finished training ([here](https://github.com/aws-samples/sagemaker-cross-validation-pipeline/blob/main/code/cv.py#L62) is a function that does this; we will be reimplementing it).
- [ ] in `estimator.fit` set `wait=False` to allow folds to train in parallel
- [ ] Design and implement unit tests with the understanding that it may not be possible to test this code without incurring costs from AWS (talk to Marmot about how they have tested their AWS utilities)

**Validation**
- [ ] When we are able to train a k-fold validated model and see that all folds are training at once (look at console).

Note: because this code will interact with AWS, it is not clear how to test this code. Should look into whether there is a viable mock for SageMaker in `moto3`.
